<?php
/**
 * Bootstrap Tabs Block
 * 
 * @package Bootstrap_Theme
 */

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Render Bootstrap Tabs Block
 */
function bootstrap_theme_render_bs_tabs_block($attributes, $content, $block) {
    $tabsId = $attributes['tabsId'] ?? 'tabs-' . uniqid();
    $vertical = $attributes['vertical'] ?? false;
    $variant = $attributes['variant'] ?? '';
    $align = $attributes['align'] ?? '';
    
    // Build tab container classes
    $classes = array('tabs-wrapper');
    
    if ($vertical) {
        $classes[] = 'd-flex';
    }
    
    // Add custom CSS classes from Advanced panel
    $classes = bootstrap_theme_add_custom_classes($classes, $attributes, $block);
    
    // Get animation data attributes
    $animation_attrs = '';
    if (function_exists('bootstrap_theme_get_animation_attributes')) {
        $animation_attrs = bootstrap_theme_get_animation_attributes($attributes, $block);
    }

    $class_string = implode(' ', array_unique($classes));

    ob_start();
    ?>
    <div class="<?php echo esc_attr($class_string); ?>"<?php echo $animation_attrs; ?>>
        <div class="<?php echo $vertical ? 'd-flex' : ''; ?>">
            <ul class="nav nav-tabs<?php echo !empty($variant) ? ' variant-' . esc_attr($variant) : ''; ?>" id="<?php echo esc_attr($tabsId); ?>" role="tablist">
                <!-- Tab buttons will be generated by JavaScript in editor -->
            </ul>
            <div class="tab-content" id="<?php echo esc_attr($tabsId); ?>-content">
                <?php echo $content; ?>
            </div>
        </div>
    </div>
    <?php
    return ob_get_clean();
}

/**
 * Register Bootstrap Tabs Block
 */
function bootstrap_theme_register_bs_tabs_block() {
    register_block_type('bootstrap-theme/bs-tabs', array(
        'render_callback' => 'bootstrap_theme_render_bs_tabs_block',
        'attributes' => array(
            'tabsId' => array(
                'type' => 'string',
                'default' => ''
            ),
            'vertical' => array(
                'type' => 'boolean',
                'default' => false
            ),
            'variant' => array(
                'type' => 'string',
                'default' => ''
            ),
            'align' => array(
                'type' => 'string',
                'default' => ''
            ),
            'className' => array(
                'type' => 'string',
                'default' => ''
            ),
            'aosAnimation' => array(
                'type' => 'string',
                'default' => ''
            ),
            'aosDelay' => array(
                'type' => 'number',
                'default' => 0
            ),
            'aosDuration' => array(
                'type' => 'number',
                'default' => 800
            ),
            'aosEasing' => array(
                'type' => 'string',
                'default' => 'ease-in-out-cubic'
            ),
            'aosOnce' => array(
                'type' => 'boolean',
                'default' => false
            ),
            'aosMirror' => array(
                'type' => 'boolean',
                'default' => true
            ),
            'aosAnchorPlacement' => array(
                'type' => 'string',
                'default' => 'top-bottom'
            )
        )
    ));
}
add_action('init', 'bootstrap_theme_register_bs_tabs_block');
